### ISSUE TITLE
5.0以下机型使用设置圆角直接崩溃

### ISSUE THREAD

**Issue by fingdo** [jiajunhui/PlayerBase#11]
```
Caused by: java.lang.NoSuchMethodError: android.view.View.setClipToOutline
        at com.kk.taurus.playerbase.style.StyleSetter.setRoundRectShape(StyleSetter.java:50)
        at com.kk.taurus.playerbase.style.StyleSetter.setRoundRectShape(StyleSetter.java:44)
        at com.kk.taurus.playerbase.widget.BaseVideoView.setRoundRectShape(BaseVideoView.java:488)
        at com.kk.taurus.avplayer.ui.VideoViewActivity.onStyleSetRoundRect(VideoViewActivity.java:163)
```
没有做兼容低版本处理嘛？如果想在5.0以下机型使用，怎么设置？

**Comment by jiajunhui** [comment]
由于使用的是系统API，5.0以下确实是用不了ViewOutlineProvider，目前这个正在处理中……

**Comment by delaiwen-hgh** [comment]
求5.0以下的圆角处理方法@ @jiajunhui

**Comment by jiajunhui** [comment]
@delaiwen-hgh Base库中使用的是系统API做的圆角。StyleSetter中API注明了RequestApi注解。5.0以下的自行处理。

**Comment by delaiwen-hgh** [comment]
尝试了一些方法,都没有用... 望大师指点迷津

**Comment by delaiwen-hgh** [comment]
@jiajunhui

**Comment by jiajunhui** [comment]
@delaiwen-hgh 试试这个吧，可能存在未知bug
https://github.com/GcsSloop/rclayout

**Comment by fingdo** [comment]
亲测rclayout使用surfaceview渲染不行，用textureview可以设置圆角

**Comment by delaiwen-hgh** [comment]
那5.0以下surfaceview圆角,老哥有方法吗 @fingdo

**Comment by fingdo** [comment]
没啥太大办法，可以用其他view设置空心的圆角背景，中间露出了一个圆角矩形去显示surface，这个就要求背景是一个纯色，或者简单简单才可以，希望能帮到你。@delaiwen-hgh

**Comment by liweiGe** [comment]
> 没啥太大办法，可以用其他view设置空心的圆角背景，中间露出了一个圆角矩形去显示surface，这个就要求背景是一个纯色，或者简单简单才可以，希望能帮到你。@delaiwen-hgh



> 那5.0以下surfaceview圆角,老哥有方法吗 @fingdo

用cardview 包裹一下喽

**Comment by feifeixiaoshizi** [comment]
5.0以下可以重写ondraw方法裁剪画布实现
