### ISSUE TITLE
部分低版本手机出现奔溃

### ISSUE THREAD

**Issue by uhongtian** [jiajunhui/PlayerBase#30]
你好👋，我的应用用了PlayerBase后，是使用了RelationAssist，在部分4.2.2手机上面出现了这个奔溃
下面是奔溃信息
Thread Name: 'main'
Back traces starts.
java.lang.RuntimeException: Error during detachFromGLContext (see logcat for details)
	at android.graphics.SurfaceTexture.attachToGLContext(SurfaceTexture.java:237)
	at android.view.GLES20TextureLayer.setSurfaceTexture(GLES20TextureLayer.java:81)
	at android.view.HardwareRenderer$Gl20Renderer.setSurfaceTexture(HardwareRenderer.java:1576)
	at android.view.TextureView.getHardwareLayer(TextureView.java:393)
	at android.view.View.getDisplayList(View.java:12806)
	at android.view.View.getDisplayList(View.java:12887)
	at android.view.View.draw(View.java:13632)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3045)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2909)
	at android.view.View.getDisplayList(View.java:12838)
	at android.view.View.getDisplayList(View.java:12887)
	at android.view.View.draw(View.java:13632)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3045)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2909)
	at android.view.View.draw(View.java:13939)
	at android.widget.FrameLayout.draw(FrameLayout.java:467)
	at android.view.View.getDisplayList(View.java:12843)
	at android.view.View.getDisplayList(View.java:12887)
	at android.view.View.draw(View.java:13632)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3045)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2909)
	at android.view.View.draw(View.java:13939)
	at android.widget.FrameLayout.draw(FrameLayout.java:467)
	at android.view.View.getDisplayList(View.java:12843)
	at android.view.View.getDisplayList(View.java:12887)
	at android.view.View.draw(View.java:13632)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3045)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2909)
	at android.view.View.draw(View.java:13939)
	at android.widget.FrameLayout.draw(FrameLayout.java:467)
	at android.view.View.getDisplayList(View.java:12843)
	at android.view.View.getDisplayList(View.java:12887)
	at android.view.View.draw(View.java:13632)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3045)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2909)
	at android.view.View.getDisplayList(View.java:12838)
	at android.view.View.getDisplayList(View.java:12887)
	at android.view.View.draw(View.java:13632)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3045)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2909)
	at android.view.View.getDisplayList(View.java:12838)
	at android.view.View.getDisplayList(View.java:12887)
	at android.view.View.draw(View.java:13632)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3045)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2909)
	at android.view.View.getDisplayList(View.java:12838)
	at android.view.View.getDisplayList(View.java:12887)
	at android.view.View.draw(View.java:13632)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3045)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2909)
	at android.view.View.draw(View.java:13939)
	at android.widget.FrameLayout.draw(FrameLayout.java:467)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2228)
	at android.view.View.getDisplayList(View.java:12843)
	at android.view.View.getDisplayList(View.java:12887)
	at android.view.HardwareRenderer$GlRenderer.draw(HardwareRenderer.java:1249)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:2523)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2390)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2192)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1181)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:4945)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:776)
	at android.view.Choreographer.doCallbacks(Choreographer.java:579)
	at android.view.Choreographer.doFrame(Choreographer.java:548)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:762)
	at android.os.Handler.handleCallback(Handler.java:800)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:194)
	at android.app.ActivityThread.main(ActivityThread.java:5409)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:525)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:897)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:664)
	at dalvik.system.NativeStart.main(Native Method)
Back traces ends.

**Comment by uhongtian** [comment]
是在使用assistPlayer play的时候，没有传DataSource就会出现这个问题

**Comment by jiajunhui** [comment]
@uhongtian 进群说吧，这里交流不便。

**Comment by frankie0802** [comment]
> @uhongtian 进群说吧，这里交流不便。

请问解决了嘛？多谢~
