### ISSUE TITLE
ReceiverGroup在时间分发的时候会有ForEach操作，这个时候add或removeReceiver，会发生异常

### ISSUE THREAD

**Issue by ifmvo** [jiajunhui/PlayerBase#62]
Process: cn.quicktv.androidpro, PID: 31661
    java.util.ConcurrentModificationException
        at java.util.ArrayList$Itr.next(ArrayList.java:860)
        at com.kk.taurus.playerbase.receiver.ReceiverGroup.forEach(ReceiverGroup.java:125)
        at com.kk.taurus.playerbase.receiver.ReceiverGroup.forEach(ReceiverGroup.java:120)
        at com.kk.taurus.playerbase.event.EventDispatcher.dispatchErrorEvent(EventDispatcher.java:86)
        at com.kk.taurus.playerbase.widget.SuperContainer.dispatchErrorEvent(SuperContainer.java:147)
        at com.kk.taurus.playerbase.widget.BaseVideoView$5.onErrorEvent(BaseVideoView.java:532)
        at com.kk.taurus.playerbase.AVPlayer.callBackErrorEventListener(AVPlayer.java:235)
        at com.kk.taurus.playerbase.AVPlayer.access$500(AVPlayer.java:42)
        at com.kk.taurus.playerbase.AVPlayer$3.onErrorEvent(AVPlayer.java:213)
        at com.kk.taurus.playerbase.player.BaseInternalPlayer.submitErrorEvent(BaseInternalPlayer.java:71)
        at cn.quicktv.androidpro.activity.playerNew.player.IjkPlayer.access$2300(IjkPlayer.java:29)
        at cn.quicktv.androidpro.activity.playerNew.player.IjkPlayer$6.onError(IjkPlayer.java:496)
        at tv.danmaku.ijk.media.player.AbstractMediaPlayer.notifyOnError(SourceFile:106)
        at tv.danmaku.ijk.media.player.IjkMediaPlayer$EventHandler.handleMessage(SourceFile:1015)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:171)
        at android.app.ActivityThread.main(ActivityThread.java:6699)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:246)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783)

**Comment by ifmvo** [comment]
CopyOnWriteArrayList是java.util.concurrent包中的一个List的实现类。CopyOnWrite的意思是在写时拷贝，也就是如果需要对CopyOnWriteArrayList的内容进行改变，首先会拷贝一份新的List并且在新的List上进行修改，最后将原List的引用指向新的List。

使用CopyOnWriteArrayList可以线程安全地遍历，因为如果另外一个线程在遍历的时候修改List的话，实际上会拷贝出一个新的List上修改，而不影响当前正在被遍历的List。

相当于校长要想从班级喊走或者添加学生，需要把学生全部带到一个新的教室再进行操作，而老师则通过之前班级的快照在照片上清点学生。

`public final class ReceiverGroup implements IReceiverGroup{
     ...
    public ReceiverGroup(GroupValue groupValue){
        ...
        mReceiverArray = new CopyOnWriteArrayList<>();
        ...
    }
`
我试了一下将 mReceiverArray 初始化成CopyOnWriteArrayList ，暂时还没有发现不良反应
