### ISSUE TITLE
RelationAssist切换解码貌似会黑屏

### ISSUE THREAD

**Issue by General110** [jiajunhui/PlayerBase#75]
RelationAssist.switchDecoder切换解码貌似会黑屏，android P

**Comment by jiajunhui** [comment]
解码器的切换属于冷切换。切换后需要再次设置数据起播。不知道你的用法是否正确。如果用法是正确的，那黑屏发生时有没有异常日志，如果有，请提供一下。

**Comment by General110** [comment]
2019-03-15 22:54:15.644 11717-11717/com.test.app I/ExoPlayerImpl: Init 9b22aff [ExoPlayerLib/2.9.1] [A0001, A0001, OnePlus, 28]
2019-03-15 22:54:15.674 11717-11717/com.test.app D/AVPlayer: =============================
2019-03-15 22:54:15.674 11717-11717/com.test.app D/AVPlayer: DecoderPlanInfo : planId      = 200
2019-03-15 22:54:15.675 11717-11717/com.test.app D/AVPlayer: DecoderPlanInfo : classPath   = com.kk.taurus.exoplayer.ExoMediaPlayer
2019-03-15 22:54:15.675 11717-11717/com.test.app D/AVPlayer: DecoderPlanInfo : desc        = exoplayer
2019-03-15 22:54:15.675 11717-11717/com.test.app D/AVPlayer: =============================
2019-03-15 22:54:15.686 11717-11717/com.test.app D/frameEvent_play: PLAYER_EVENT_ON_PROVIDER_DATA_START
2019-03-15 22:54:15.739 11717-11939/com.test.app W/Adreno-EGL: <qeglDrvAPI_eglGetConfigAttrib:607>: EGL_BAD_ATTRIBUTE
2019-03-15 22:54:15.740 11717-11939/com.test.app D/vndksupport: Loading /vendor/lib/hw/gralloc.msm8974.so from current namespace instead of sphal namespace.
2019-03-15 22:54:15.750 11717-11717/com.test.app D/AVPlayer: onProviderDataSuccessMediaData : DataSource = com.kk.taurus.playerbase.entity.DataSource@19c19da
2019-03-15 22:54:15.750 11717-11717/com.test.app D/frameEvent_play: PLAYER_EVENT_ON_STATUS_CHANGE
2019-03-15 22:54:15.776 11717-11717/com.test.app D/ExoMediaPlayer: onPlayerStateChanged : playWhenReady = false, playbackState = 2
2019-03-15 22:54:15.776 11717-11717/com.test.app D/frameEvent_play: PLAYER_EVENT_ON_DATA_SOURCE_SET
2019-03-15 22:54:15.792 11717-11717/com.test.app D/ExoMediaPlayer: onPlayerStateChanged : playWhenReady = true, playbackState = 2
2019-03-15 22:54:15.798 11717-11717/com.test.app D/frameEvent_play: PLAYER_EVENT_ON_PROVIDER_DATA_SUCCESS
2019-03-15 22:54:15.810 11717-11717/com.test.app D/frameEvent_play: PLAYER_EVENT_ON_TIMER_UPDATE, curr = 0,duration = 1,bufferPercentage = 0
2019-03-15 22:54:16.287 11717-11717/com.test.app D/ExoMediaPlayer: onLoadingChanged : true, bufferPercentage = 0
2019-03-15 22:54:16.816 11717-11717/com.test.app D/frameEvent_play: PLAYER_EVENT_ON_TIMER_UPDATE, curr = 0,duration = 2452159,bufferPercentage = 0
2019-03-15 22:54:16.959 11717-12164/com.test.app W/VideoCapabilities: Unrecognized profile 4 for video/hevc
2019-03-15 22:54:16.965 11717-12164/com.test.app W/VideoCapabilities: Unrecognized profile/level 0/3 for video/mpeg2
2019-03-15 22:54:16.970 11717-12164/com.test.app W/VideoCapabilities: Unrecognized profile/level 0/3 for video/mpeg2
2019-03-15 22:54:16.996 11717-12164/com.test.app W/VideoCapabilities: Unrecognized profile 2130706433 for video/avc
2019-03-15 22:54:17.024 11717-12164/com.test.app I/VideoCapabilities: Unsupported profile 4 for video/mp4v-es
2019-03-15 22:54:17.065 11717-12180/com.test.app I/OMXClient: IOmx service obtained
2019-03-15 22:54:17.086 11717-12185/com.test.app W/Adreno-EGL: <qeglDrvAPI_eglGetConfigAttrib:607>: EGL_BAD_ATTRIBUTE
2019-03-15 22:54:17.089 11717-12185/com.test.app W/Adreno-EGL: <qeglDrvAPI_eglQueryContext:4370>: EGL_BAD_ATTRIBUTE
2019-03-15 22:54:17.093 11717-12179/com.test.app D/SurfaceUtils: connecting to surface 0x83c22008, reason connectToSurface
2019-03-15 22:54:17.093 11717-12179/com.test.app I/MediaCodec: [OMX.qcom.video.decoder.avc] setting surface generation to 11998209
2019-03-15 22:54:17.093 11717-12179/com.test.app D/SurfaceUtils: disconnecting from surface 0x83c22008, reason connectToSurface(reconnect)
2019-03-15 22:54:17.093 11717-12179/com.test.app D/SurfaceUtils: connecting to surface 0x83c22008, reason connectToSurface(reconnect)
2019-03-15 22:54:17.122 11717-12180/com.test.app D/SurfaceUtils: set up nativeWindow 0x83c22008 for 1920x1080, color 0x7fa30c04, rotation 0, usage 0x42002900
2019-03-15 22:54:17.135 11717-12180/com.test.app I/Gralloc2: Adding additional valid usage bits: 0x2200000
2019-03-15 22:54:17.136 11717-12180/com.test.app W/MapperHal: buffer descriptor with invalid usage bits 0x2002000
2019-03-15 22:54:17.141 11717-12180/com.test.app W/MapperHal: buffer descriptor with invalid usage bits 0x2002000
2019-03-15 22:54:17.143 11717-12187/com.test.app I/OMXClient: IOmx service obtained
2019-03-15 22:54:17.144 11717-12180/com.test.app W/MapperHal: buffer descriptor with invalid usage bits 0x2002000
2019-03-15 22:54:17.149 11717-12180/com.test.app W/MapperHal: buffer descriptor with invalid usage bits 0x2002000
2019-03-15 22:54:17.152 11717-12187/com.test.app I/ACodec: codec does not support config priority (err -2147483648)
2019-03-15 22:54:17.163 11717-11717/com.test.app D/ExoMediaPlayer: onPlayerStateChanged : playWhenReady = true, playbackState = 3
2019-03-15 22:54:17.163 11717-11717/com.test.app D/frameEvent_play: PLAYER_EVENT_ON_STATUS_CHANGE
2019-03-15 22:54:17.166 11717-11717/com.test.app D/frameEvent_play: PLAYER_EVENT_ON_SURFACE_UPDATE
2019-03-15 22:54:17.166 11717-12180/com.test.app W/MapperHal: buffer descriptor with invalid usage bits 0x2002000
2019-03-15 22:54:17.166 11717-11717/com.test.app D/RenderTextureView: ****bindSurface****
2019-03-15 22:54:17.166 11717-11717/com.test.app D/frameEvent_play: PLAYER_EVENT_ON_PREPARED
2019-03-15 22:54:17.166 11717-11717/com.test.app D/frameEvent_play: PLAYER_EVENT_ON_STATUS_CHANGE
2019-03-15 22:54:17.169 11717-12180/com.test.app W/MapperHal: buffer descriptor with invalid usage bits 0x2002000
2019-03-15 22:54:17.171 11717-11717/com.test.app D/frameEvent_play: PLAYER_EVENT_ON_START
2019-03-15 22:54:17.173 11717-12180/com.test.app W/MapperHal: buffer descriptor with invalid usage bits 0x2002000
2019-03-15 22:54:17.181 11717-12180/com.test.app W/MapperHal: buffer descriptor with invalid usage bits 0x2002000
**2019-03-15 22:54:17.200 11717-12164/com.test.app E/ExoPlayerImplInternal: Internal runtime error.
    java.lang.IllegalArgumentException: The surface has been released
        at android.media.MediaCodec.native_setSurface(Native Method)
        at android.media.MediaCodec.setOutputSurface(MediaCodec.java:1979)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.setOutputSurfaceV23(MediaCodecVideoRenderer.java:1014)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.setSurface(MediaCodecVideoRenderer.java:422)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.handleMessage(MediaCodecVideoRenderer.java:387)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.deliverMessage(ExoPlayerImplInternal.java:871)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.sendMessageToTarget(ExoPlayerImplInternal.java:842)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.sendMessageInternal(ExoPlayerImplInternal.java:824)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:333)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:193)
        at android.os.HandlerThread.run(HandlerThread.java:65)**
2019-03-15 22:54:17.229 11717-12179/com.test.app D/SurfaceUtils: disconnecting from surface 0x83c22008, reason disconnectFromSurface
2019-03-15 22:54:17.274 11717-11717/com.test.app E/ExoMediaPlayer: java.lang.IllegalArgumentException: The surface has been released
2019-03-15 22:54:17.274 11717-11717/com.test.app E/frameEvent_error: ERROR_EVENT_UNKNOWN
2019-03-15 22:54:17.277 11717-11717/com.test.app D/ExoMediaPlayer: onLoadingChanged : false, bufferPercentage = 0
2019-03-15 22:54:17.277 11717-11717/com.test.app D/ExoMediaPlayer: onPlayerStateChanged : playWhenReady = true, playbackState = 1
2019-03-15 22:54:17.278 11717-11717/com.test.app D/frameEvent_play: PLAYER_EVENT_ON_STATUS_CHANGE
2019-03-15 22:54:17.280 11717-11717/com.test.app D/frameEvent_play: PLAYER_EVENT_ON_RESUME
2019-03-15 22:54:17.296 11717-11717/com.test.app D/frameEvent_play: PLAYER_EVENT_ON_TIMER_UPDATE, curr = 139164,duration = 2452159,bufferPercentage = 0
2019-03-15 22:54:18.302 11717-11717/com.test.app D/frameEvent_play: PLAYER_EVENT_ON_TIMER_UPDATE, curr = 139164,duration = 2452159,bufferPercentage = 0
2019-03-15 22:54:19.307 11717-11717/com.test.app D/frameEvent_play: PLAYER_EVENT_ON_TIMER_UPDATE, curr = 139164,duration = 2452159,bufferPercentage = 0
2019-03-15 22:54:19.379 11717-11717/com.test.app D/GestureCallbackHandler: onDown...
2019-03-15 22:54:19.479 11717-11717/com.test.app D/ControllerCover: requestNotifyTimer...
2019-03-15 22:54:19.480 11717-11717/com.test.app E/TimerCounterProxy: Timer Started
2019-03-15 22:54:19.518 11717-11717/com.test.app D/frameEvent_play: PLAYER_EVENT_ON_TIMER_UPDATE, curr = 139164,duration = 2452159,bufferPercentage = 0
2019-03-15 22:54:20.538 11717-11717/com.test.app D/frameEvent_play: PLAYER_EVENT_ON_TIMER_UPDATE, curr = 139164,duration = 2452159,bufferPercentage = 0

**Comment by General110** [comment]
2019-03-15 22:54:17.171 11717-11717/com.test.app D/frameEvent_play: PLAYER_EVENT_ON_START
2019-03-15 22:54:17.173 11717-12180/com.test.app W/MapperHal: buffer descriptor with invalid usage bits 0x2002000
2019-03-15 22:54:17.181 11717-12180/com.test.app W/MapperHal: buffer descriptor with invalid usage bits 0x2002000
**2019-03-15 22:54:17.200 11717-12164/com.test.app E/ExoPlayerImplInternal: Internal runtime error.
    java.lang.IllegalArgumentException: The surface has been released
        at android.media.MediaCodec.native_setSurface(Native Method)
        at android.media.MediaCodec.setOutputSurface(MediaCodec.java:1979)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.setOutputSurfaceV23(MediaCodecVideoRenderer.java:1014)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.setSurface(MediaCodecVideoRenderer.java:422)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.handleMessage(MediaCodecVideoRenderer.java:387)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.deliverMessage(ExoPlayerImplInternal.java:871)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.sendMessageToTarget(ExoPlayerImplInternal.java:842)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.sendMessageInternal(ExoPlayerImplInternal.java:824)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:333)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:193)
        at android.os.HandlerThread.run(HandlerThread.java:65)**
2019-03-15 22:54:17.229 11717-12179/com.test.app D/SurfaceUtils: disconnecting from surface 0x83c22008, reason disconnectFromSurface
2019-03-15 22:54:17.274 11717-11717/com.test.app E/ExoMediaPlayer: java.lang.IllegalArgumentException: The surface has been released
2019-03-15 22:54:17.274 11717-11717/com.test.app E/frameEvent_error: ERROR_EVENT_UNKNOWN
2019-03-15 22:54:17.277 11717-11717/com.test.app D/ExoMediaPlayer: onLoadingChanged : false, bufferPercentage = 0
2019-03-15 22:54:17.277 11717-11717/com.test.app D/ExoMediaPlayer: onPlayerStateChanged : playWhenReady = true, playbackState = 1





在android 6上没事,在Android 9上就出现黑屏。

**Comment by jiajunhui** [comment]
@General110 是只有切到EXO时报这个错吗？还有你的具体操作步骤。最好进群详聊一下。

**Comment by General110** [comment]
抱歉，最近太忙没回复！
由于我切换解码器后，忘记Assist.attachContainer(VideoContainer);导致的。
感谢大佬热情的回复
